In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [4]:
## preprocess the data
## drop irrelevant feature
data = data.drop(['RowNumber','CustomerId', 'Surname'], axis=1)

KeyError: "['RowNumber', 'CustomerId', 'Surname'] not found in axis"

In [5]:
## Encode categorical variables
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])

In [6]:
## OneHot encode 'Geography'
onehot_encoder_geo=OneHotEncoder(handle_unknown='ignore')
geo_encoded=onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [8]:
## combine one hot encoder columns with the original data
data=pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

KeyError: "['Geography'] not found in axis"

In [9]:
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [10]:
## divide the dataset into independent and dependent features
x = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [11]:
## split the data in training and testing sets
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [12]:
##scale these features
scaler=StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [13]:
## save the encoders and sca-learn
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)
    
with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)
    
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

## ANN Regression Problem Statements

In [14]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [15]:
## build our ann model
model=Sequential([
    Dense(64,activation='relu',input_shape=(x_train.shape[1],)), ## first hidden layer connected with input
    Dense(32, activation='relu'), ## hidden layer 2
    Dense(1) ## output layer
    ]
)

## compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

C:\Users\sonup\AppData\Roaming\Python\Python311\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Create a unique log directory with timestamp
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

# TensorBoard callback
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [ ]:
## set up early stopping
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [18]:
## train the model
history=model.fit(
    x_train,y_train,validation_data=(x_test,y_test),epochs=100,
    callbacks=[tensorboard_callback,early_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 100382.9922 - mae: 100382.9922 - val_loss: 98535.2031 - val_mae: 98535.2031
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 99693.6484 - mae: 99693.6484 - val_loss: 97135.7969 - val_mae: 97135.7969
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 97252.8125 - mae: 97252.8125 - val_loss: 93550.4375 - val_mae: 93550.4375
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 92447.0625 - mae: 92447.0625 - val_loss: 87541.9297 - val_mae: 87541.9297
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 85361.9844 - mae: 85361.9844 - val_loss: 79593.5859 - val_mae: 79593.5859
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 76805.8906 - mae: 76805.8906 - val_loss: 71133.4297 - val_mae: 71133.4297
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 68212.2734 - mae: 68212.2734 - val_loss: 63484.9453 - val_mae: 63484.9453
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 60993.3984 - mae: 60993.3984 - val_loss: 57715.5273 - val_mae: 57715.5273
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 56066.8203 - mae: 56066.8203 - val_loss: 54153.8125 - val_mae: 54153.8125
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 53134.7969 - mae: 53134.7969 - val_loss: 52343.3750 - val_mae: 52343.3750
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 51602.6953 - mae: 51602.6953 - val_loss: 51598.2266 - val_mae: 51598.2266
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 50937.8047 - mae: 50937.8047 - val_loss: 51332.9062 - val_mae: 51332.9062
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 50650.9453 - mae: 50650.9453 - val_loss: 51198.6523 - val_mae: 51198.6523
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50493.3086 - mae: 50493.3086 - val_loss: 51108.6484 - val_mae: 51108.6484
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 50393.0586 - mae: 50393.0586 - val_loss: 51021.5156 - val_mae: 51021.5156
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50313.5000 - mae: 50313.5000 - val_loss: 50954.9648 - val_mae: 50954.9648
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50245.7578 - mae: 50245.7578 - val_loss: 50892.9141 - val_mae: 50892.9141
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50184.3867 - mae: 50184.3867 - val_loss: 50847.1055 - val_mae: 50847.1055
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50135.6797 - mae: 50135.6797 - val_loss: 50803.2188 - val_mae: 50803.2188
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50086.2539 - mae: 50086.2539 - val_loss: 50759.2188 - val_mae: 50759.2188
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50044.9102 - mae: 50044.9102 - val_loss: 50722.8164 - val_mae: 50722.8164
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50004.3750 - mae: 50004.3750 - val_loss: 50688.3984 - val_mae: 50688.3984
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49968.4570 - mae: 49968.4570 - val_loss: 50660.0664 - val_mae: 50660.0664
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49934.6914 - mae: 49934.6914 - val_loss: 50627.6094 - val_mae: 50627.6094
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49900.1719 - mae: 49900.1719 - val_loss: 50608.8945 - val_mae: 50608.8945
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49868.5430 - mae: 49868.5430 - val_loss: 50579.5156 - val_mae: 50579.5156
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49840.3516 - mae: 49840.3516 - val_loss: 50554.3633 - val_mae: 50554.3633
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49816.4336 - mae: 49816.4336 - val_loss: 50525.1445 - val_mae: 50525.1445
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 49792.3359 - mae: 49792.3359 - val_loss: 50502.6133 - val_mae: 50502.6133
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49769.1133 - mae: 49769.1133 - val_loss: 50486.7617 - val_mae: 50486.7617
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 49745.2969 - mae: 49745.2969 - val_loss: 50470.0938 - val_mae: 50470.0938
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49728.2539 - mae: 49728.2539 - val_loss: 50450.2383 - val_mae: 50450.2383
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49710.7031 - mae: 49710.7031 - val_loss: 50427.5273 - val_mae: 50427.5273
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49693.4336 - mae: 49693.4336 - val_loss: 50420.3516 - val_mae: 50420.3516
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 49676.0156 - mae: 49676.0156 - val_loss: 50404.8242 - val_mae: 50404.8242
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49659.2266 - mae: 49659.2266 - val_loss: 50397.2227 - val_mae: 50397.2227
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49643.2969 - mae: 49643.2969 - val_loss: 50377.7617 - val_mae: 50377.7617
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49630.0039 - mae: 49630.0039 - val_loss: 50376.9023 - val_mae: 50376.9023
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49616.7344 - mae: 49616.7344 - val_loss: 50369.3047 - val_mae: 50369.3047
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 49605.8984 - mae: 49605.8984 - val_loss: 50359.7539 - val_mae: 50359.7539
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49592.4961 - mae: 49592.4961 - val_loss: 50353.5039 - val_mae: 50353.5039
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49577.5312 - mae: 49577.5312 - val_loss: 50347.3555 - val_mae: 50347.3555
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 49567.6758 - mae: 49567.6758 - val_loss: 50337.4141 - val_mae: 50337.4141
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 49559.8828 - mae: 49559.8828 - val_loss: 50333.3594 - val_mae: 50333.3594
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49548.0898 - mae: 49548.0898 - val_loss: 50334.5156 - val_mae: 50334.5156
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49537.0703 - mae: 49537.0703 - val_loss: 50332.8281 - val_mae: 50332.8281
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 49529.8828 - mae: 49529.8828 - val_loss: 50331.9531 - val_mae: 50331.9531
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49522.2188 - mae: 49522.2188 - val_loss: 50324.9023 - val_mae: 50324.9023
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49514.2305 - mae: 49514.2305 - val_loss: 50315.8867 - val_mae: 50315.8867
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49502.1836 - mae: 49502.1836 - val_loss: 50312.7422 - val_mae: 50312.7422
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49496.8672 - mae: 49496.8672 - val_loss: 50310.0195 - val_mae: 50310.0195
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49487.5977 - mae: 49487.5977 - val_loss: 50311.2109 - val_mae: 50311.2109
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49481.6875 - mae: 49481.6875 - val_loss: 50315.8750 - val_mae: 50315.8750
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 49473.4023 - mae: 49473.4023 - val_loss: 50306.2891 - val_mae: 50306.2891
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 49468.4570 - mae: 49468.4570 - val_loss: 50314.6562 - val_mae: 50314.6562
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49460.6250 - mae: 49460.6250 - val_loss: 50302.3555 - val_mae: 50302.3555
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49453.7852 - mae: 49453.7852 - val_loss: 50295.9961 - val_mae: 50295.9961
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49449.1875 - mae: 49449.1875 - val_loss: 50303.3984 - val_mae: 50303.3984
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49442.6680 - mae: 49442.6680 - val_loss: 50299.7539 - val_mae: 50299.7539
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 49437.3086 - mae: 49437.3086 - val_loss: 50303.6211 - val_mae: 50303.6211
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49432.4883 - mae: 49432.4883 - val_loss: 50296.5742 - val_mae: 50296.5742
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49428.7617 - mae: 49428.7617 - val_loss: 50298.0938 - val_mae: 50298.0938

In [19]:
## load tensorboard extension
%load_ext tensorboard

In [22]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6006 (pid 17984), started 0:00:23 ago. (Use '!kill 17984' to kill it.)

In [23]:
##  evaluagte model on the test data
test_loss,test_mae=model.evaluate(x_test,y_test)
print(f'Test MAE: {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 50295.9961 - mae: 50295.9961
Test MAE: 50295.99609375

In [25]:
model.save('regression_model.keras')